#Embedded file name: c:/depot/games/branches/release/EVE-TRANQUILITY/eve/client/script/ui/shared/infoPanels/infoPanelConst.py
import util
PANEL_LOCATION_INFO = 1
PANEL_ROUTE = 2
PANEL_MISSIONS = 3
PANEL_INCURSIONS = 4
PANEL_FACTIONAL_WARFARE = 5
PANEL_PLANETARY_INTERACTION = 6
PANELTYPES = (PANEL_LOCATION_INFO,
 PANEL_ROUTE,
 PANEL_MISSIONS,
 PANEL_INCURSIONS,
 PANEL_FACTIONAL_WARFARE,
 PANEL_PLANETARY_INTERACTION)
MODE_NORMAL = 1
MODE_COMPACT = 2
MODE_COLLAPSED = 3
PANELWIDTH = 312
LEFTPAD = 42
exports = util.AutoExports('infoPanel', locals())